// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mizumoto-cn/ratingo/pkg/data/ent/analysis"
	"github.com/mizumoto-cn/ratingo/pkg/data/ent/topic"
)

// AnalysisCreate is the builder for creating a Analysis entity.
type AnalysisCreate struct {
	config
	mutation *AnalysisMutation
	hooks    []Hook
}

// SetTopicID sets the "topic_id" field.
func (ac *AnalysisCreate) SetTopicID(i int) *AnalysisCreate {
	ac.mutation.SetTopicID(i)
	return ac
}

// SetAvgRating sets the "avg_rating" field.
func (ac *AnalysisCreate) SetAvgRating(f float64) *AnalysisCreate {
	ac.mutation.SetAvgRating(f)
	return ac
}

// SetID sets the "id" field.
func (ac *AnalysisCreate) SetID(i int) *AnalysisCreate {
	ac.mutation.SetID(i)
	return ac
}

// SetUnderTopicOfID sets the "underTopicOf" edge to the Topic entity by ID.
func (ac *AnalysisCreate) SetUnderTopicOfID(id int) *AnalysisCreate {
	ac.mutation.SetUnderTopicOfID(id)
	return ac
}

// SetNillableUnderTopicOfID sets the "underTopicOf" edge to the Topic entity by ID if the given value is not nil.
func (ac *AnalysisCreate) SetNillableUnderTopicOfID(id *int) *AnalysisCreate {
	if id != nil {
		ac = ac.SetUnderTopicOfID(*id)
	}
	return ac
}

// SetUnderTopicOf sets the "underTopicOf" edge to the Topic entity.
func (ac *AnalysisCreate) SetUnderTopicOf(t *Topic) *AnalysisCreate {
	return ac.SetUnderTopicOfID(t.ID)
}

// Mutation returns the AnalysisMutation object of the builder.
func (ac *AnalysisCreate) Mutation() *AnalysisMutation {
	return ac.mutation
}

// Save creates the Analysis in the database.
func (ac *AnalysisCreate) Save(ctx context.Context) (*Analysis, error) {
	var (
		err  error
		node *Analysis
	)
	if len(ac.hooks) == 0 {
		if err = ac.check(); err != nil {
			return nil, err
		}
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AnalysisMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ac.check(); err != nil {
				return nil, err
			}
			ac.mutation = mutation
			if node, err = ac.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			if ac.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ac.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ac.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Analysis)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AnalysisMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AnalysisCreate) SaveX(ctx context.Context) *Analysis {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AnalysisCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AnalysisCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AnalysisCreate) check() error {
	if _, ok := ac.mutation.TopicID(); !ok {
		return &ValidationError{Name: "topic_id", err: errors.New(`ent: missing required field "Analysis.topic_id"`)}
	}
	if _, ok := ac.mutation.AvgRating(); !ok {
		return &ValidationError{Name: "avg_rating", err: errors.New(`ent: missing required field "Analysis.avg_rating"`)}
	}
	return nil
}

func (ac *AnalysisCreate) sqlSave(ctx context.Context) (*Analysis, error) {
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (ac *AnalysisCreate) createSpec() (*Analysis, *sqlgraph.CreateSpec) {
	var (
		_node = &Analysis{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: analysis.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: analysis.FieldID,
			},
		}
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.TopicID(); ok {
		_spec.SetField(analysis.FieldTopicID, field.TypeInt, value)
		_node.TopicID = value
	}
	if value, ok := ac.mutation.AvgRating(); ok {
		_spec.SetField(analysis.FieldAvgRating, field.TypeFloat64, value)
		_node.AvgRating = value
	}
	if nodes := ac.mutation.UnderTopicOfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   analysis.UnderTopicOfTable,
			Columns: []string{analysis.UnderTopicOfColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: topic.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.topic_analysis = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AnalysisCreateBulk is the builder for creating many Analysis entities in bulk.
type AnalysisCreateBulk struct {
	config
	builders []*AnalysisCreate
}

// Save creates the Analysis entities in the database.
func (acb *AnalysisCreateBulk) Save(ctx context.Context) ([]*Analysis, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Analysis, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnalysisMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AnalysisCreateBulk) SaveX(ctx context.Context) []*Analysis {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AnalysisCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AnalysisCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
