// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mizumoto-cn/ratingo/pkg/data/ent/analysis"
	"github.com/mizumoto-cn/ratingo/pkg/data/ent/predicate"
	"github.com/mizumoto-cn/ratingo/pkg/data/ent/topic"
)

// AnalysisQuery is the builder for querying Analysis entities.
type AnalysisQuery struct {
	config
	limit            *int
	offset           *int
	unique           *bool
	order            []OrderFunc
	fields           []string
	predicates       []predicate.Analysis
	withUnderTopicOf *TopicQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AnalysisQuery builder.
func (aq *AnalysisQuery) Where(ps ...predicate.Analysis) *AnalysisQuery {
	aq.predicates = append(aq.predicates, ps...)
	return aq
}

// Limit adds a limit step to the query.
func (aq *AnalysisQuery) Limit(limit int) *AnalysisQuery {
	aq.limit = &limit
	return aq
}

// Offset adds an offset step to the query.
func (aq *AnalysisQuery) Offset(offset int) *AnalysisQuery {
	aq.offset = &offset
	return aq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aq *AnalysisQuery) Unique(unique bool) *AnalysisQuery {
	aq.unique = &unique
	return aq
}

// Order adds an order step to the query.
func (aq *AnalysisQuery) Order(o ...OrderFunc) *AnalysisQuery {
	aq.order = append(aq.order, o...)
	return aq
}

// QueryUnderTopicOf chains the current query on the "underTopicOf" edge.
func (aq *AnalysisQuery) QueryUnderTopicOf() *TopicQuery {
	query := &TopicQuery{config: aq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(analysis.Table, analysis.FieldID, selector),
			sqlgraph.To(topic.Table, topic.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, analysis.UnderTopicOfTable, analysis.UnderTopicOfColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Analysis entity from the query.
// Returns a *NotFoundError when no Analysis was found.
func (aq *AnalysisQuery) First(ctx context.Context) (*Analysis, error) {
	nodes, err := aq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{analysis.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aq *AnalysisQuery) FirstX(ctx context.Context) *Analysis {
	node, err := aq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Analysis ID from the query.
// Returns a *NotFoundError when no Analysis ID was found.
func (aq *AnalysisQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{analysis.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aq *AnalysisQuery) FirstIDX(ctx context.Context) int {
	id, err := aq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Analysis entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Analysis entity is found.
// Returns a *NotFoundError when no Analysis entities are found.
func (aq *AnalysisQuery) Only(ctx context.Context) (*Analysis, error) {
	nodes, err := aq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{analysis.Label}
	default:
		return nil, &NotSingularError{analysis.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aq *AnalysisQuery) OnlyX(ctx context.Context) *Analysis {
	node, err := aq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Analysis ID in the query.
// Returns a *NotSingularError when more than one Analysis ID is found.
// Returns a *NotFoundError when no entities are found.
func (aq *AnalysisQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{analysis.Label}
	default:
		err = &NotSingularError{analysis.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aq *AnalysisQuery) OnlyIDX(ctx context.Context) int {
	id, err := aq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Analyses.
func (aq *AnalysisQuery) All(ctx context.Context) ([]*Analysis, error) {
	if err := aq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return aq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (aq *AnalysisQuery) AllX(ctx context.Context) []*Analysis {
	nodes, err := aq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Analysis IDs.
func (aq *AnalysisQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := aq.Select(analysis.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aq *AnalysisQuery) IDsX(ctx context.Context) []int {
	ids, err := aq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aq *AnalysisQuery) Count(ctx context.Context) (int, error) {
	if err := aq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return aq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (aq *AnalysisQuery) CountX(ctx context.Context) int {
	count, err := aq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aq *AnalysisQuery) Exist(ctx context.Context) (bool, error) {
	if err := aq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return aq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (aq *AnalysisQuery) ExistX(ctx context.Context) bool {
	exist, err := aq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AnalysisQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aq *AnalysisQuery) Clone() *AnalysisQuery {
	if aq == nil {
		return nil
	}
	return &AnalysisQuery{
		config:           aq.config,
		limit:            aq.limit,
		offset:           aq.offset,
		order:            append([]OrderFunc{}, aq.order...),
		predicates:       append([]predicate.Analysis{}, aq.predicates...),
		withUnderTopicOf: aq.withUnderTopicOf.Clone(),
		// clone intermediate query.
		sql:    aq.sql.Clone(),
		path:   aq.path,
		unique: aq.unique,
	}
}

// WithUnderTopicOf tells the query-builder to eager-load the nodes that are connected to
// the "underTopicOf" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AnalysisQuery) WithUnderTopicOf(opts ...func(*TopicQuery)) *AnalysisQuery {
	query := &TopicQuery{config: aq.config}
	for _, opt := range opts {
		opt(query)
	}
	aq.withUnderTopicOf = query
	return aq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TopicID int `json:"topic_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Analysis.Query().
//		GroupBy(analysis.FieldTopicID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aq *AnalysisQuery) GroupBy(field string, fields ...string) *AnalysisGroupBy {
	grbuild := &AnalysisGroupBy{config: aq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return aq.sqlQuery(ctx), nil
	}
	grbuild.label = analysis.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TopicID int `json:"topic_id,omitempty"`
//	}
//
//	client.Analysis.Query().
//		Select(analysis.FieldTopicID).
//		Scan(ctx, &v)
func (aq *AnalysisQuery) Select(fields ...string) *AnalysisSelect {
	aq.fields = append(aq.fields, fields...)
	selbuild := &AnalysisSelect{AnalysisQuery: aq}
	selbuild.label = analysis.Label
	selbuild.flds, selbuild.scan = &aq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a AnalysisSelect configured with the given aggregations.
func (aq *AnalysisQuery) Aggregate(fns ...AggregateFunc) *AnalysisSelect {
	return aq.Select().Aggregate(fns...)
}

func (aq *AnalysisQuery) prepareQuery(ctx context.Context) error {
	for _, f := range aq.fields {
		if !analysis.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aq.path != nil {
		prev, err := aq.path(ctx)
		if err != nil {
			return err
		}
		aq.sql = prev
	}
	return nil
}

func (aq *AnalysisQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Analysis, error) {
	var (
		nodes       = []*Analysis{}
		withFKs     = aq.withFKs
		_spec       = aq.querySpec()
		loadedTypes = [1]bool{
			aq.withUnderTopicOf != nil,
		}
	)
	if aq.withUnderTopicOf != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, analysis.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Analysis).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Analysis{config: aq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := aq.withUnderTopicOf; query != nil {
		if err := aq.loadUnderTopicOf(ctx, query, nodes, nil,
			func(n *Analysis, e *Topic) { n.Edges.UnderTopicOf = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (aq *AnalysisQuery) loadUnderTopicOf(ctx context.Context, query *TopicQuery, nodes []*Analysis, init func(*Analysis), assign func(*Analysis, *Topic)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Analysis)
	for i := range nodes {
		if nodes[i].topic_analysis == nil {
			continue
		}
		fk := *nodes[i].topic_analysis
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(topic.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "topic_analysis" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (aq *AnalysisQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aq.querySpec()
	_spec.Node.Columns = aq.fields
	if len(aq.fields) > 0 {
		_spec.Unique = aq.unique != nil && *aq.unique
	}
	return sqlgraph.CountNodes(ctx, aq.driver, _spec)
}

func (aq *AnalysisQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := aq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (aq *AnalysisQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   analysis.Table,
			Columns: analysis.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: analysis.FieldID,
			},
		},
		From:   aq.sql,
		Unique: true,
	}
	if unique := aq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := aq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, analysis.FieldID)
		for i := range fields {
			if fields[i] != analysis.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aq *AnalysisQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aq.driver.Dialect())
	t1 := builder.Table(analysis.Table)
	columns := aq.fields
	if len(columns) == 0 {
		columns = analysis.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aq.sql != nil {
		selector = aq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aq.unique != nil && *aq.unique {
		selector.Distinct()
	}
	for _, p := range aq.predicates {
		p(selector)
	}
	for _, p := range aq.order {
		p(selector)
	}
	if offset := aq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AnalysisGroupBy is the group-by builder for Analysis entities.
type AnalysisGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (agb *AnalysisGroupBy) Aggregate(fns ...AggregateFunc) *AnalysisGroupBy {
	agb.fns = append(agb.fns, fns...)
	return agb
}

// Scan applies the group-by query and scans the result into the given value.
func (agb *AnalysisGroupBy) Scan(ctx context.Context, v any) error {
	query, err := agb.path(ctx)
	if err != nil {
		return err
	}
	agb.sql = query
	return agb.sqlScan(ctx, v)
}

func (agb *AnalysisGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range agb.fields {
		if !analysis.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := agb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := agb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (agb *AnalysisGroupBy) sqlQuery() *sql.Selector {
	selector := agb.sql.Select()
	aggregation := make([]string, 0, len(agb.fns))
	for _, fn := range agb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(agb.fields)+len(agb.fns))
		for _, f := range agb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(agb.fields...)...)
}

// AnalysisSelect is the builder for selecting fields of Analysis entities.
type AnalysisSelect struct {
	*AnalysisQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (as *AnalysisSelect) Aggregate(fns ...AggregateFunc) *AnalysisSelect {
	as.fns = append(as.fns, fns...)
	return as
}

// Scan applies the selector query and scans the result into the given value.
func (as *AnalysisSelect) Scan(ctx context.Context, v any) error {
	if err := as.prepareQuery(ctx); err != nil {
		return err
	}
	as.sql = as.AnalysisQuery.sqlQuery(ctx)
	return as.sqlScan(ctx, v)
}

func (as *AnalysisSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(as.fns))
	for _, fn := range as.fns {
		aggregation = append(aggregation, fn(as.sql))
	}
	switch n := len(*as.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		as.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		as.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := as.sql.Query()
	if err := as.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
