// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Analysis is the predicate function for analysis builders.
type Analysis func(*sql.Selector)

// Rating is the predicate function for rating builders.
type Rating func(*sql.Selector)

// Topic is the predicate function for topic builders.
type Topic func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
